### PR TITLE
im not a genius but im gonna guess this will fix issue #19

### PR DESCRIPTION
**Pull request by m626zNq**

### CODE REVIEW

**Comment by m626zNq** [comment]
#19 @codergautam

**Comment by m626zNq** [comment]
@maxwoollons can you possibly test this on your phone? thanks

**Comment by maxwoollons** [comment]
> @maxwoollons can you possibly test this on your phone? thanks

I will get to this hopefully this afternoon

**Comment by m626zNq** [comment]
> > @maxwoollons can you possibly test this on your phone? thanks
> 
> I will get to this hopefully this afternoon

Any luck?

**Comment by codergautam** [comment]
merging to my dev branch, I will be testing this over the weekend

**Pull request merged**
